Process Instance Definition
digi-serve/appbuilder_platform_service pull request #120
Opened 2024-06-25 09:40 UTC by nh758

https://github.com/digi-serve/ab_service_process_manager/issues/87
## Release Notes

- save process instance definition as JSON in a new table
 

## Test Status
- added unit tests

2024-06-25 19:36 UTC, Hiro-Nakamura requested changes
This looks good!

Just a minor update and Good to go!

2024-06-25 19:36 UTC, Hiro-Nakamura commented on platform/ABProcess.js
> +            process: this,
minor issue: but now when I go through error dumps, I prefer to reduce the amount of info being dumped.  So a `this.toObj()` would be better here than the raw object and all the additional data it includes.

2024-06-26 07:55 UTC, wongpratan approved these changes

2024-06-26 17:40 UTC, Hiro-Nakamura approved these changes
LGTM

2024-06-27 02:22 UTC, merged